# Generated by Django 2.1.7 on 2019-06-11 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets_liabilities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liabilities',
            old_name='DueDate',
            new_name='due_date',
        ),
        migrations.RemoveField(
            model_name='liabilities',
            name='StartDate',
        ),
    ]
