# Generated by Django 2.1.7 on 2019-06-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20190612_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expenses',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='s_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
