# Generated by Django 2.1.7 on 2019-06-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20190612_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('account_no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=4)),
                ('balance', models.IntegerField()),
                ('account_type', models.CharField(choices=[('AS', 'Asset'), ('LI', 'Liability'), ('CA', 'Capital'), ('EX', 'Expense')], max_length=4, null=True)),
            ],
        ),
    ]
