# Generated by Django 2.1.7 on 2019-06-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20190612_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
