# Generated by Django 2.1.7 on 2019-06-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('cus_no', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=14)),
                ('last_name', models.CharField(max_length=16, null=True)),
                ('ID', models.PositiveIntegerField(null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('balance', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.PositiveIntegerField(null=True)),
            ],
            options={
                'db_table': 'customers',
                'ordering': ['first_name'],
            },
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('sup_no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('balance', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.PositiveIntegerField(null=True)),
            ],
            options={
                'db_table': 'suppliers',
                'ordering': ['name'],
            },
        ),
    ]
